### ISSUE TITLE
Context capture mode not working (2.5.2). App is crashing

### ISSUE THREAD

**Issue by tmillettweather** [Smartling/android-repository#12]
08-30 13:15:02.573 18047-19369/com.application E/TWCUncaughtExcptnHandler: Uncaught exception in thread: Thread[ContextCapture,5,main]
                                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
                                                                                   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at com.smartling.android.shared.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:32)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at com.smartling.android.shared.network.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:36)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                                   at okhttp3.RealCall.execute(RealCall.java:63)
                                                                                   at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46)
                                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                                   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                                                   at com.smartling.android.review.context.service.ContextWorker.loadStrings(SourceFile:104)
                                                                                   at com.smartling.android.review.context.service.ContextServiceHandler.a(SourceFile:111)
                                                                                   at com.smartling.android.review.context.service.ContextServiceHandler.handleMessage(SourceFile:58)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.application-2/base.apk", zip file "/data/app/com.application-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.application2/split_lib_slice_1_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.applicationr-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.applicationr-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.application-2/lib/arm64, /data/app/com.application-2/base.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                   at com.smartling.android.shared.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:32) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                   at com.smartling.android.shared.network.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:36) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
                                                                                   at okhttp3.RealCall.execute(RealCall.java:63) 
                                                                                   at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46) 
                                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 
                                                                                   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89) 
                                                                                   at com.smartling.android.review.context.service.ContextWorker.loadStrings(SourceFile:104) 
                                                                                   at com.smartling.android.review.context.service.ContextServiceHandler.a(SourceFile:111) 
                                                                                   at com.smartling.android.review.context.service.ContextServiceHandler.handleMessage(SourceFile:58) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
08-30 13:15:02.575 18047-19369/com.application E/AndroidRuntime: FATAL EXCEPTION: ContextCapture
                                                                     Process: com.application, PID: 18047
                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at com.smartling.android.shared.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:32)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at com.smartling.android.shared.network.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:36)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                         at okhttp3.RealCall.execute(RealCall.java:63)
                                                                         at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46)
                                                                         at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                         at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                                         at com.smartling.android.review.context.service.ContextWorker.loadStrings(SourceFile:104)
                                                                         at com.smartling.android.review.context.service.ContextServiceHandler.a(SourceFile:111)
                                                                         at com.smartling.android.review.context.service.ContextServiceHandler.handleMessage(SourceFile:58)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.application-2/base.apk", zip file "/data/app/com.application-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.application-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.application-2/lib/arm64, /data/app/com.application-2/base.apk!/lib/arm64-v8a, /data/app/com.applicationr-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.application-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                         at com.smartling.android.shared.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:32) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                         at com.smartling.android.shared.network.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:36) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
                                                                         at okhttp3.RealCall.execute(RealCall.java:63) 
                                                                         at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46) 
                                                                         at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 
                                                                         at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89) 
                                                                         at com.smartling.android.review.context.service.ContextWorker.loadStrings(SourceFile:104) 
                                                                         at com.smartling.android.review.context.service.ContextServiceHandler.a(SourceFile:111) 
                                                                         at com.smartling.android.review.context.service.ContextServiceHandler.handleMessage(SourceFile:58) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by foo4u** [comment]
@tmillettweather this is a multi-dex build, correct?

**Comment by andriipanasiuk** [comment]
Hey @tmillettweather 
I guess the reason is in the mismatch between `okhttp` version we're using. Even if you're not using it explicitly it's included in `retrofit` artifact and some others.
Provide please the output of your `./gradlew app:dependencies` command. I need the fragments with `com.squareup.retrofit2:retrofit`, `com.squareup.okhttp3:logging-interceptor` and `com.squareup.okhttp3:okhttp` only.
Thanks!

**Comment by tmillettweather** [comment]
Sorry for the late reply.  Below are all the okhttp fragments that I found.

|    +--- com.squareup.okhttp3:okhttp:3.6.0
|    |    \--- com.squareup.okio:okio:1.11.0
|    +--- com.squareup.okhttp3:okhttp-urlconnection:3.6.0
|    |    \--- com.squareup.okhttp3:okhttp:3.6.0 (*)
|    +--- com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0
|    |    +--- com.squareup.picasso:picasso:2.5.2
|    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.6.0 (*)


  |    |    |    \--- com.squareup.okhttp3:okhttp:3.2.0
     |    |    |         \--- com.squareup.okio:okio:1.6.0
     |    |    +--- com.squareup.retrofit2:converter-gson:2.0.2
     |    |    |    +--- com.squareup.retrofit2:retrofit:2.0.2 (*)
     |    |    |    \--- com.google.code.gson:gson:2.6.1
     |    |    +--- com.squareup.okhttp3:logging-interceptor:3.2.0
     |    |    |    \--- com.squareup.okhttp3:okhttp:3.2.0 (*)

|    +--- com.squareup.okhttp3:logging-interceptor:3.2.0 (*)

|    |    +--- com.squareup.okhttp3:logging-interceptor:3.2.0
|    |    |    \--- com.squareup.okhttp3:okhttp:3.2.0 -> 3.6.0 (*)
|    |    +--- com.github.Raizlabs.DBFlow:dbflow-core:4.0.5

**Comment by foo4u** [comment]
@tmillettweather looks like `okhttp3/internal/http/HttpEngine` was removed between OkHttp 3.2.0 and 3.6.0. I see Gradle's dependency resolution bumping our SDK's request for 3.2.0 to 3.6.0 but the logging interceptor is still at 3.2.0. From above:

```
+--- com.squareup.okhttp3:logging-interceptor:3.2.0
        \ --- com.squareup.okhttp3:okhttp:3.2.0 -> 3.6.0 (*)
```

If you could please declare in your `build.gradle` a dependency on `com.squareup.okhttp3:logging-interceptor:3.6.0` (match the version of OkHttp you're requesting) it should fix the issue.

Please confirm. If that works we can investigate if there's a way to make sure dependencies okhttp3 logging interceptor and okhttp3 proper's versions align.

**Comment by tmillettweather** [comment]
@foo4u It looks like it is working, and it is not crashing anymore.  While using the context-capture I can login and send screenshots to smartling, and verified that I could see them on the dashboard.
